//! Conservative, sleeping background cleanup, independent of capture/rendering.
use std::{
    fs, io,
    os::windows::fs::MetadataExt,
    path::{Path, PathBuf},
    sync::mpsc::{self, RecvTimeoutError, Sender},
    thread::{self, JoinHandle},
    time::{Duration, SystemTime},
};

use anyhow::Result;

const RETENTION: Duration = Duration::from_secs(24 * 60 * 60);
const INTERVAL: Duration = Duration::from_secs(60 * 60);
const REPARSE_POINT: u32 = 0x400;

pub struct CleanupWorker {
    stop: Sender<()>,
    thread: Option<JoinHandle<()>>,
}

impl CleanupWorker {
    pub fn start(folder: PathBuf) -> Result<Self> {
        let (stop, receiver) = mpsc::channel();
        let thread = thread::Builder::new()
            .name("screenshot-cleanup".into())
            .spawn(move || loop {
                match sweep(&folder, SystemTime::now()) {
                    Ok(report) => {
                        if report.removed > 0 || report.failed > 0 {
                            println!(
                                "Temp cleanup: {} removed, {} deferred (locked or inaccessible)",
                                report.removed, report.failed
                            );
                        }
                    }
                    Err(error) => eprintln!("Temp cleanup failed: {error}"),
                }
                match receiver.recv_timeout(INTERVAL) {
                    Err(RecvTimeoutError::Timeout) => (),
                    _ => break,
                }
            })?;
        Ok(Self {
            stop,
            thread: Some(thread),
        })
    }
}

impl Drop for CleanupWorker {
    fn drop(&mut self) {
        let _ = self.stop.send(());
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

#[derive(Default, Debug)]
struct Report {
    removed: usize,
    failed: usize,
}

// Only names generated by storage::save_png, including abandoned private writes.
fn owned_filename(name: &str) -> bool {
    let Some(stem) = name
        .strip_suffix(".png.part")
        .or_else(|| name.strip_suffix(".png"))
        .and_then(|name| name.strip_prefix("shot_"))
    else {
        return false;
    };
    let parts: Vec<_> = stem.split('_').collect();
    parts.len() == 3
        && parts
            .iter()
            .all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
}

fn sweep(folder: &Path, now: SystemTime) -> io::Result<Report> {
    let mut report = Report::default();
    let metadata = match fs::symlink_metadata(folder) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(report),
        Err(error) => return Err(error),
    };
    // Do not traverse junctions/symlinks or recurse into child directories.
    if !metadata.is_dir() || metadata.file_attributes() & REPARSE_POINT != 0 {
        return Ok(report);
    }
    for entry in fs::read_dir(folder)? {
        let result = (|| -> io::Result<()> {
            let entry = entry?;
            if !entry.file_name().to_str().is_some_and(owned_filename) {
                return Ok(());
            }
            let metadata = fs::symlink_metadata(entry.path())?;
            if !metadata.is_file() || metadata.file_attributes() & REPARSE_POINT != 0 {
                return Ok(());
            }
            // A future timestamp (clock correction) is never considered expired.
            if now
                .duration_since(metadata.modified()?)
                .is_ok_and(|age| age >= RETENTION)
            {
                match fs::remove_file(entry.path()) {
                    Ok(()) => report.removed += 1,
                    Err(error) if error.kind() == io::ErrorKind::NotFound => (),
                    Err(error) => return Err(error),
                }
            }
            Ok(())
        })();
        if result.is_err() {
            report.failed += 1;
        }
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::{File, FileTimes};

    struct Folder(PathBuf);
    impl Folder {
        fn new() -> Result<Self> {
            let stamp = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)?
                .as_nanos();
            let path = std::env::temp_dir().join(format!(
                "screenshot cleanup 日本 {} {stamp}",
                std::process::id()
            ));
            fs::create_dir(&path)?;
            Ok(Self(path))
        }
        fn file(&self, name: &str, modified: SystemTime) -> Result<PathBuf> {
            let path = self.0.join(name);
            let file = File::create(&path)?;
            file.set_times(FileTimes::new().set_modified(modified))?;
            Ok(path)
        }
    }
    impl Drop for Folder {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn filenames_are_strictly_scoped() {
        for name in ["shot_123_42_0.png", "shot_123_42_1.png.part"] {
            assert!(owned_filename(name));
        }
        for name in [
            "photo.png",
            "shot_backup.png",
            "shot_1_2.png",
            "shot_1_2_3_4.png",
            "shot__2_3.png",
            "shot_1_2_a.png",
            "shot_1_2_3.PNG",
        ] {
            assert!(!owned_filename(name));
        }
    }

    #[test]
    fn only_expired_owned_files_and_abandoned_writes_are_removed() -> Result<()> {
        let folder = Folder::new()?;
        let now = SystemTime::now();
        let old = now - RETENTION - Duration::from_secs(1);
        let expired = folder.file("shot_1_2_3.png", old)?;
        let pending = folder.file("shot_1_2_4.png.part", old)?;
        let boundary = folder.file("shot_1_2_5.png", now - RETENTION)?;
        let fresh = folder.file("shot_1_2_6.png", now - RETENTION + Duration::from_secs(1))?;
        let future = folder.file("shot_1_2_7.png", now + Duration::from_secs(60))?;
        let unrelated = folder.file("personal.png", old)?;
        let directory = folder.0.join("shot_1_2_8.png");
        fs::create_dir(&directory)?;
        let report = sweep(&folder.0, now)?;
        assert_eq!(report.removed, 3);
        assert_eq!(report.failed, 0);
        for path in [expired, pending, boundary] {
            assert!(!path.exists());
        }
        for path in [fresh, future, unrelated, directory] {
            assert!(path.exists());
        }
        Ok(())
    }

    #[test]
    fn active_screenshot_is_deferred_until_guard_is_released() -> Result<()> {
        let folder = Folder::new()?;
        let now = SystemTime::now();
        let path = folder.file("shot_1_2_3.png", now - RETENTION - Duration::from_secs(1))?;
        let guard = crate::storage::protect_png(&path)?;
        let report = sweep(&folder.0, now)?;
        assert_eq!(report.removed, 0);
        assert_eq!(report.failed, 1);
        assert!(path.exists());
        // Copy/read consumers must remain compatible with the protection handle.
        fs::copy(&path, folder.0.join("copy.png"))?;
        drop(guard);
        assert_eq!(sweep(&folder.0, now)?.removed, 1);
        Ok(())
    }

    #[test]
    fn missing_folder_is_normal_and_sleeping_worker_stops_promptly() -> Result<()> {
        let folder = Folder::new()?;
        assert_eq!(
            sweep(&folder.0.join("missing"), SystemTime::now())?.removed,
            0
        );
        let worker = CleanupWorker::start(folder.0.clone())?;
        drop(worker);
        Ok(())
    }
}
